name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile steal
      run: sudo make
    - name: Install steal
      run: sudo make install
    - name: test package manager
      run: sudo steal update
